### ISSUE TITLE
Discord bot only works in the official server because of the way we enforce testing channel

### ISSUE THREAD

**Issue by OmerSabic** [Adonis-Self-Improvement/ASI-DiscordBot#42]
**Is your feature request related to a problem? Please describe.**
The bot doesn't work on local dev environments due to it enforcing the testing channel by ID instead of something more dynamic.

**Describe the solution you'd like**
Either have the admins enforce the discord bot's typing permission with roles or enforce channel by name

**Comment by vlyr** [comment]
Closed by #43.
