### ISSUE TITLE
Yarn or NPM?

### ISSUE THREAD

**Issue by vlyr** [Adonis-Self-Improvement/ASI-DiscordBot#44]
**Is your feature request related to a problem? Please describe.**
We have two lockfiles on the repository, Updating with NPM changes Yarn's lockfile as well, causing conflicts that must be solved manually.

**Describe the solution you'd like**
A decision on which **one** package manager we start using.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by seanjhardy** [comment]
Not sure what we're doing with this, but we should just use NPM, idk how to remove the yarn file so please feel free

**Comment by vlyr** [comment]
Closed by #54.
